name: Go

on:
  push:
    branches: [build-on-macos]

permissions:
  contents: read
  statuses: write

jobs:
  test-build:
    name: Test build
    strategy:
      matrix:
        go-version: [1.16.x]
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Build
      run: ./build
