name: Go

on:
  push:
    branches: [build-on-macos]

permissions:
  contents: read
  statuses: write

jobs:
  test-build:
    name: Test build
    strategy:
      matrix:
        go-version: [1.15.x]
    runs-on: macos-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        path: checkout_butane
        persist-credentials: false
    - name: Build
      run: cd checkout_butane && ./build
    - name: Run butane --version
      run: ./checkout_butane/bin/amd64/butane --version

